### ISSUE TITLE
itchat 都的功能都能用了吗

### ISSUE THREAD

**Issue by 377123** [wechaty/python-wechaty-puppet-itchat#2]

**Comment by lyleshaw** [comment]
不好意思哈，这个是我的开源之夏将要完成的任务->[https://github.com/wechaty/summer-of-wechaty/issues/75](https://github.com/wechaty/summer-of-wechaty/issues/75) ，目前仅仅停留在初期，还未完善。 
完成整个项目可能需要到八月底左右。
如果需要使用UOS版Itchat可以跳转[https://github.com/luvletter2333/ItChat ](https://github.com/luvletter2333/ItChat ),作者为Itchat添加了UOS头，使得普通微信号也可以恢复web微信的使用。
如果对该项目感兴趣，可以等到项目完成时再通知您～

**Comment by lyleshaw** [comment]
目前 `python-wechaty-puppet-itchat` 的大部分功能已经可用（含收发消息，搜索用户等）。

欢迎您体验并反馈问题。

**Comment by wj-Mcat** [comment]
It's time to make a comparison list with other protocol in readme. Let's do it as soon as possible.
