### ISSUE TITLE
wechaty-puppet-service: token not found. please set

### ISSUE THREAD

**Issue by feavar** [wechaty/python-wechaty-puppet-itchat#20]
wechaty_puppet.exceptions.WechatyPuppetConfigurationError: WechatyPuppetConfigurationError('wechaty-puppet-service: token not found. please set environment<WECHATY_PUPPET_SERVICE_TOKEN|TOKEN|token> as token', None, None)

Please tell me where to set the token?

**Comment by lyleshaw** [comment]
Can you show the code to let me locate the problem?

Thank you very much~

**Comment by feavar** [comment]
def get_token():
    """
    get the token from environment variable
    """
    return os.environ.get('WECHATY_PUPPET_SERVICE_TOKEN', None) or \
        os.environ.get('TOKEN', None) or \
        os.environ.get('token', None) or None

I found it, I may to set the environment variable.

**Comment by lyleshaw** [comment]
python-wechaty-puppet-itchat is a web protocol puppet in python language, you don't need to set token.
