### ISSUE TITLE
【Feature 💁 💁】CICD is required for opensource project

### ISSUE THREAD

**Issue by wj-Mcat** [wechaty/python-wechaty-puppet-itchat#3]
CI (Continuous integration) is the key tools that can keep the quality of project. It will create the strict rule for all of developers  . It's only when pr pass the CI test, it will be merged into master branch. Please refer to: [Makefile](https://github.com/wechaty/python-wechaty/blob/master/Makefile) to add CI test to this repo. I will review the new pr.

CD(continuous delivery) will delivery the new version of package when it arises the new change. Eg, when the new pr is merged into the [python-wechaty](https://github.com/wechaty/python-wechaty) repo, it will automatically deploy the new [wechaty](https://pypi.org/project/wechaty/)  by CD. 

CICD is the base structure for the good opensource project, this repo should add it.

## reference
* [What is CI/CD? Continuous integration and continuous delivery explained](https://www.infoworld.com/article/3271126/what-is-cicd-continuous-integration-and-continuous-delivery-explained.html)
* [python-wechaty CI test](https://github.com/wechaty/python-wechaty/blob/master/Makefile)
* [packaging the project](https://packaging.python.org/tutorials/packaging-projects/)
* [github about-continuous-integration](https://docs.github.com/en/actions/guides/about-continuous-integration)
* [python-wechaty cd workflow](https://github.com/wechaty/python-wechaty/blob/master/.github/workflows/pypi.yml)

**Comment by lyleshaw** [comment]
Got it.👌
